image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

BuildStage:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

TestStage:
  stage: test
  script: npm test